echo chor001-sop; grouper -p parameters.txt chor001-sop.nb > ../../boundaries/chor/chor001-sop.bd
echo chor002-sop; grouper -p parameters.txt chor002-sop.nb > ../../boundaries/chor/chor002-sop.bd
echo chor003-sop; grouper -p parameters.txt chor003-sop.nb > ../../boundaries/chor/chor003-sop.bd
echo chor004-sop; grouper -p parameters.txt chor004-sop.nb > ../../boundaries/chor/chor004-sop.bd
echo chor005-sop; grouper -p parameters.txt chor005-sop.nb > ../../boundaries/chor/chor005-sop.bd
echo chor006-sop; grouper -p parameters.txt chor006-sop.nb > ../../boundaries/chor/chor006-sop.bd
echo chor007-sop; grouper -p parameters.txt chor007-sop.nb > ../../boundaries/chor/chor007-sop.bd
echo chor008-sop; grouper -p parameters.txt chor008-sop.nb > ../../boundaries/chor/chor008-sop.bd
echo chor009-sop; grouper -p parameters.txt chor009-sop.nb > ../../boundaries/chor/chor009-sop.bd
echo chor010-sop; grouper -p parameters.txt chor010-sop.nb > ../../boundaries/chor/chor010-sop.bd
echo chor011-sop; grouper -p parameters.txt chor011-sop.nb > ../../boundaries/chor/chor011-sop.bd
echo chor012-sop; grouper -p parameters.txt chor012-sop.nb > ../../boundaries/chor/chor012-sop.bd
echo chor013-sop; grouper -p parameters.txt chor013-sop.nb > ../../boundaries/chor/chor013-sop.bd
echo chor014-sop; grouper -p parameters.txt chor014-sop.nb > ../../boundaries/chor/chor014-sop.bd
echo chor015-sop; grouper -p parameters.txt chor015-sop.nb > ../../boundaries/chor/chor015-sop.bd
echo chor016-sop; grouper -p parameters.txt chor016-sop.nb > ../../boundaries/chor/chor016-sop.bd
echo chor017-sop; grouper -p parameters.txt chor017-sop.nb > ../../boundaries/chor/chor017-sop.bd
echo chor018-sop; grouper -p parameters.txt chor018-sop.nb > ../../boundaries/chor/chor018-sop.bd
echo chor019-sop; grouper -p parameters.txt chor019-sop.nb > ../../boundaries/chor/chor019-sop.bd
echo chor020-sop; grouper -p parameters.txt chor020-sop.nb > ../../boundaries/chor/chor020-sop.bd
echo chor021-sop; grouper -p parameters.txt chor021-sop.nb > ../../boundaries/chor/chor021-sop.bd
echo chor022-sop; grouper -p parameters.txt chor022-sop.nb > ../../boundaries/chor/chor022-sop.bd
echo chor023-sop; grouper -p parameters.txt chor023-sop.nb > ../../boundaries/chor/chor023-sop.bd
echo chor024-sop; grouper -p parameters.txt chor024-sop.nb > ../../boundaries/chor/chor024-sop.bd
echo chor025-sop; grouper -p parameters.txt chor025-sop.nb > ../../boundaries/chor/chor025-sop.bd
echo chor026-sop; grouper -p parameters.txt chor026-sop.nb > ../../boundaries/chor/chor026-sop.bd
echo chor027-sop; grouper -p parameters.txt chor027-sop.nb > ../../boundaries/chor/chor027-sop.bd
echo chor028-sop; grouper -p parameters.txt chor028-sop.nb > ../../boundaries/chor/chor028-sop.bd
echo chor029-sop; grouper -p parameters.txt chor029-sop.nb > ../../boundaries/chor/chor029-sop.bd
echo chor030-sop; grouper -p parameters.txt chor030-sop.nb > ../../boundaries/chor/chor030-sop.bd
echo chor031-sop; grouper -p parameters.txt chor031-sop.nb > ../../boundaries/chor/chor031-sop.bd
echo chor032-sop; grouper -p parameters.txt chor032-sop.nb > ../../boundaries/chor/chor032-sop.bd
echo chor033-sop; grouper -p parameters.txt chor033-sop.nb > ../../boundaries/chor/chor033-sop.bd
echo chor034-sop; grouper -p parameters.txt chor034-sop.nb > ../../boundaries/chor/chor034-sop.bd
echo chor035-sop; grouper -p parameters.txt chor035-sop.nb > ../../boundaries/chor/chor035-sop.bd
echo chor036-sop; grouper -p parameters.txt chor036-sop.nb > ../../boundaries/chor/chor036-sop.bd
echo chor037-sop; grouper -p parameters.txt chor037-sop.nb > ../../boundaries/chor/chor037-sop.bd
echo chor038-sop; grouper -p parameters.txt chor038-sop.nb > ../../boundaries/chor/chor038-sop.bd
echo chor039-sop; grouper -p parameters.txt chor039-sop.nb > ../../boundaries/chor/chor039-sop.bd
echo chor040-sop; grouper -p parameters.txt chor040-sop.nb > ../../boundaries/chor/chor040-sop.bd
echo chor041-sop; grouper -p parameters.txt chor041-sop.nb > ../../boundaries/chor/chor041-sop.bd
echo chor042-sop; grouper -p parameters.txt chor042-sop.nb > ../../boundaries/chor/chor042-sop.bd
echo chor043-sop; grouper -p parameters.txt chor043-sop.nb > ../../boundaries/chor/chor043-sop.bd
echo chor044-sop; grouper -p parameters.txt chor044-sop.nb > ../../boundaries/chor/chor044-sop.bd
echo chor045-sop; grouper -p parameters.txt chor045-sop.nb > ../../boundaries/chor/chor045-sop.bd
echo chor046-sop; grouper -p parameters.txt chor046-sop.nb > ../../boundaries/chor/chor046-sop.bd
echo chor047-sop; grouper -p parameters.txt chor047-sop.nb > ../../boundaries/chor/chor047-sop.bd
echo chor048-sop; grouper -p parameters.txt chor048-sop.nb > ../../boundaries/chor/chor048-sop.bd
echo chor049-sop; grouper -p parameters.txt chor049-sop.nb > ../../boundaries/chor/chor049-sop.bd
echo chor050-sop; grouper -p parameters.txt chor050-sop.nb > ../../boundaries/chor/chor050-sop.bd
echo chor051-sop; grouper -p parameters.txt chor051-sop.nb > ../../boundaries/chor/chor051-sop.bd
echo chor052-sop; grouper -p parameters.txt chor052-sop.nb > ../../boundaries/chor/chor052-sop.bd
echo chor053-sop; grouper -p parameters.txt chor053-sop.nb > ../../boundaries/chor/chor053-sop.bd
echo chor054-sop; grouper -p parameters.txt chor054-sop.nb > ../../boundaries/chor/chor054-sop.bd
echo chor055-sop; grouper -p parameters.txt chor055-sop.nb > ../../boundaries/chor/chor055-sop.bd
echo chor056-sop; grouper -p parameters.txt chor056-sop.nb > ../../boundaries/chor/chor056-sop.bd
echo chor057-sop; grouper -p parameters.txt chor057-sop.nb > ../../boundaries/chor/chor057-sop.bd
echo chor058-sop; grouper -p parameters.txt chor058-sop.nb > ../../boundaries/chor/chor058-sop.bd
echo chor059-sop; grouper -p parameters.txt chor059-sop.nb > ../../boundaries/chor/chor059-sop.bd
echo chor060-sop; grouper -p parameters.txt chor060-sop.nb > ../../boundaries/chor/chor060-sop.bd
echo chor061-sop; grouper -p parameters.txt chor061-sop.nb > ../../boundaries/chor/chor061-sop.bd
echo chor062-sop; grouper -p parameters.txt chor062-sop.nb > ../../boundaries/chor/chor062-sop.bd
echo chor063-sop; grouper -p parameters.txt chor063-sop.nb > ../../boundaries/chor/chor063-sop.bd
echo chor064-sop; grouper -p parameters.txt chor064-sop.nb > ../../boundaries/chor/chor064-sop.bd
echo chor065-sop; grouper -p parameters.txt chor065-sop.nb > ../../boundaries/chor/chor065-sop.bd
echo chor066-sop; grouper -p parameters.txt chor066-sop.nb > ../../boundaries/chor/chor066-sop.bd
echo chor067-sop; grouper -p parameters.txt chor067-sop.nb > ../../boundaries/chor/chor067-sop.bd
echo chor068-sop; grouper -p parameters.txt chor068-sop.nb > ../../boundaries/chor/chor068-sop.bd
echo chor069-sop; grouper -p parameters.txt chor069-sop.nb > ../../boundaries/chor/chor069-sop.bd
echo chor070-sop; grouper -p parameters.txt chor070-sop.nb > ../../boundaries/chor/chor070-sop.bd
echo chor071-sop; grouper -p parameters.txt chor071-sop.nb > ../../boundaries/chor/chor071-sop.bd
echo chor072-sop; grouper -p parameters.txt chor072-sop.nb > ../../boundaries/chor/chor072-sop.bd
echo chor073-sop; grouper -p parameters.txt chor073-sop.nb > ../../boundaries/chor/chor073-sop.bd
echo chor074-sop; grouper -p parameters.txt chor074-sop.nb > ../../boundaries/chor/chor074-sop.bd
echo chor075-sop; grouper -p parameters.txt chor075-sop.nb > ../../boundaries/chor/chor075-sop.bd
echo chor076-sop; grouper -p parameters.txt chor076-sop.nb > ../../boundaries/chor/chor076-sop.bd
echo chor077-sop; grouper -p parameters.txt chor077-sop.nb > ../../boundaries/chor/chor077-sop.bd
echo chor078-sop; grouper -p parameters.txt chor078-sop.nb > ../../boundaries/chor/chor078-sop.bd
echo chor079-sop; grouper -p parameters.txt chor079-sop.nb > ../../boundaries/chor/chor079-sop.bd
echo chor080-sop; grouper -p parameters.txt chor080-sop.nb > ../../boundaries/chor/chor080-sop.bd
echo chor081-sop; grouper -p parameters.txt chor081-sop.nb > ../../boundaries/chor/chor081-sop.bd
echo chor082-sop; grouper -p parameters.txt chor082-sop.nb > ../../boundaries/chor/chor082-sop.bd
echo chor083-sop; grouper -p parameters.txt chor083-sop.nb > ../../boundaries/chor/chor083-sop.bd
echo chor084-sop; grouper -p parameters.txt chor084-sop.nb > ../../boundaries/chor/chor084-sop.bd
echo chor085-sop; grouper -p parameters.txt chor085-sop.nb > ../../boundaries/chor/chor085-sop.bd
echo chor086-sop; grouper -p parameters.txt chor086-sop.nb > ../../boundaries/chor/chor086-sop.bd
echo chor087-sop; grouper -p parameters.txt chor087-sop.nb > ../../boundaries/chor/chor087-sop.bd
echo chor088-sop; grouper -p parameters.txt chor088-sop.nb > ../../boundaries/chor/chor088-sop.bd
echo chor089-sop; grouper -p parameters.txt chor089-sop.nb > ../../boundaries/chor/chor089-sop.bd
echo chor090-sop; grouper -p parameters.txt chor090-sop.nb > ../../boundaries/chor/chor090-sop.bd
echo chor091-sop; grouper -p parameters.txt chor091-sop.nb > ../../boundaries/chor/chor091-sop.bd
echo chor092-sop; grouper -p parameters.txt chor092-sop.nb > ../../boundaries/chor/chor092-sop.bd
echo chor093-sop; grouper -p parameters.txt chor093-sop.nb > ../../boundaries/chor/chor093-sop.bd
echo chor094-sop; grouper -p parameters.txt chor094-sop.nb > ../../boundaries/chor/chor094-sop.bd
echo chor095-sop; grouper -p parameters.txt chor095-sop.nb > ../../boundaries/chor/chor095-sop.bd
echo chor096-sop; grouper -p parameters.txt chor096-sop.nb > ../../boundaries/chor/chor096-sop.bd
echo chor097-sop; grouper -p parameters.txt chor097-sop.nb > ../../boundaries/chor/chor097-sop.bd
echo chor098-sop; grouper -p parameters.txt chor098-sop.nb > ../../boundaries/chor/chor098-sop.bd
echo chor099-sop; grouper -p parameters.txt chor099-sop.nb > ../../boundaries/chor/chor099-sop.bd
echo chor100-sop; grouper -p parameters.txt chor100-sop.nb > ../../boundaries/chor/chor100-sop.bd
echo chor101-sop; grouper -p parameters.txt chor101-sop.nb > ../../boundaries/chor/chor101-sop.bd
echo chor102-sop; grouper -p parameters.txt chor102-sop.nb > ../../boundaries/chor/chor102-sop.bd
echo chor103-sop; grouper -p parameters.txt chor103-sop.nb > ../../boundaries/chor/chor103-sop.bd
echo chor104-sop; grouper -p parameters.txt chor104-sop.nb > ../../boundaries/chor/chor104-sop.bd
echo chor105-sop; grouper -p parameters.txt chor105-sop.nb > ../../boundaries/chor/chor105-sop.bd
echo chor106-sop; grouper -p parameters.txt chor106-sop.nb > ../../boundaries/chor/chor106-sop.bd
echo chor107-sop; grouper -p parameters.txt chor107-sop.nb > ../../boundaries/chor/chor107-sop.bd
echo chor108-sop; grouper -p parameters.txt chor108-sop.nb > ../../boundaries/chor/chor108-sop.bd
echo chor109-sop; grouper -p parameters.txt chor109-sop.nb > ../../boundaries/chor/chor109-sop.bd
echo chor110-sop; grouper -p parameters.txt chor110-sop.nb > ../../boundaries/chor/chor110-sop.bd
echo chor111-sop; grouper -p parameters.txt chor111-sop.nb > ../../boundaries/chor/chor111-sop.bd
echo chor112-sop; grouper -p parameters.txt chor112-sop.nb > ../../boundaries/chor/chor112-sop.bd
echo chor113-sop; grouper -p parameters.txt chor113-sop.nb > ../../boundaries/chor/chor113-sop.bd
echo chor114-sop; grouper -p parameters.txt chor114-sop.nb > ../../boundaries/chor/chor114-sop.bd
echo chor115-sop; grouper -p parameters.txt chor115-sop.nb > ../../boundaries/chor/chor115-sop.bd
echo chor116-sop; grouper -p parameters.txt chor116-sop.nb > ../../boundaries/chor/chor116-sop.bd
echo chor117-sop; grouper -p parameters.txt chor117-sop.nb > ../../boundaries/chor/chor117-sop.bd
echo chor118-sop; grouper -p parameters.txt chor118-sop.nb > ../../boundaries/chor/chor118-sop.bd
echo chor119-sop; grouper -p parameters.txt chor119-sop.nb > ../../boundaries/chor/chor119-sop.bd
echo chor120-sop; grouper -p parameters.txt chor120-sop.nb > ../../boundaries/chor/chor120-sop.bd
echo chor121-sop; grouper -p parameters.txt chor121-sop.nb > ../../boundaries/chor/chor121-sop.bd
echo chor122-sop; grouper -p parameters.txt chor122-sop.nb > ../../boundaries/chor/chor122-sop.bd
echo chor123-sop; grouper -p parameters.txt chor123-sop.nb > ../../boundaries/chor/chor123-sop.bd
echo chor124-sop; grouper -p parameters.txt chor124-sop.nb > ../../boundaries/chor/chor124-sop.bd
echo chor125-sop; grouper -p parameters.txt chor125-sop.nb > ../../boundaries/chor/chor125-sop.bd
echo chor126-sop; grouper -p parameters.txt chor126-sop.nb > ../../boundaries/chor/chor126-sop.bd
echo chor127-sop; grouper -p parameters.txt chor127-sop.nb > ../../boundaries/chor/chor127-sop.bd
echo chor128-sop; grouper -p parameters.txt chor128-sop.nb > ../../boundaries/chor/chor128-sop.bd
echo chor129-sop; grouper -p parameters.txt chor129-sop.nb > ../../boundaries/chor/chor129-sop.bd
echo chor130-sop; grouper -p parameters.txt chor130-sop.nb > ../../boundaries/chor/chor130-sop.bd
echo chor131-sop; grouper -p parameters.txt chor131-sop.nb > ../../boundaries/chor/chor131-sop.bd
echo chor132-sop; grouper -p parameters.txt chor132-sop.nb > ../../boundaries/chor/chor132-sop.bd
echo chor133-sop; grouper -p parameters.txt chor133-sop.nb > ../../boundaries/chor/chor133-sop.bd
echo chor134-sop; grouper -p parameters.txt chor134-sop.nb > ../../boundaries/chor/chor134-sop.bd
echo chor135-sop; grouper -p parameters.txt chor135-sop.nb > ../../boundaries/chor/chor135-sop.bd
echo chor136-sop; grouper -p parameters.txt chor136-sop.nb > ../../boundaries/chor/chor136-sop.bd
echo chor137-sop; grouper -p parameters.txt chor137-sop.nb > ../../boundaries/chor/chor137-sop.bd
echo chor138-sop; grouper -p parameters.txt chor138-sop.nb > ../../boundaries/chor/chor138-sop.bd
echo chor139-sop; grouper -p parameters.txt chor139-sop.nb > ../../boundaries/chor/chor139-sop.bd
echo chor140-sop; grouper -p parameters.txt chor140-sop.nb > ../../boundaries/chor/chor140-sop.bd
echo chor141-sop; grouper -p parameters.txt chor141-sop.nb > ../../boundaries/chor/chor141-sop.bd
echo chor142-sop; grouper -p parameters.txt chor142-sop.nb > ../../boundaries/chor/chor142-sop.bd
echo chor143-sop; grouper -p parameters.txt chor143-sop.nb > ../../boundaries/chor/chor143-sop.bd
echo chor144-sop; grouper -p parameters.txt chor144-sop.nb > ../../boundaries/chor/chor144-sop.bd
echo chor145-sop; grouper -p parameters.txt chor145-sop.nb > ../../boundaries/chor/chor145-sop.bd
echo chor146-sop; grouper -p parameters.txt chor146-sop.nb > ../../boundaries/chor/chor146-sop.bd
echo chor147-sop; grouper -p parameters.txt chor147-sop.nb > ../../boundaries/chor/chor147-sop.bd
echo chor148-sop; grouper -p parameters.txt chor148-sop.nb > ../../boundaries/chor/chor148-sop.bd
echo chor149-sop; grouper -p parameters.txt chor149-sop.nb > ../../boundaries/chor/chor149-sop.bd
echo chor151-sop; grouper -p parameters.txt chor151-sop.nb > ../../boundaries/chor/chor151-sop.bd
echo chor152-sop; grouper -p parameters.txt chor152-sop.nb > ../../boundaries/chor/chor152-sop.bd
echo chor153-sop; grouper -p parameters.txt chor153-sop.nb > ../../boundaries/chor/chor153-sop.bd
echo chor154-sop; grouper -p parameters.txt chor154-sop.nb > ../../boundaries/chor/chor154-sop.bd
echo chor155-sop; grouper -p parameters.txt chor155-sop.nb > ../../boundaries/chor/chor155-sop.bd
echo chor156-sop; grouper -p parameters.txt chor156-sop.nb > ../../boundaries/chor/chor156-sop.bd
echo chor157-sop; grouper -p parameters.txt chor157-sop.nb > ../../boundaries/chor/chor157-sop.bd
echo chor158-sop; grouper -p parameters.txt chor158-sop.nb > ../../boundaries/chor/chor158-sop.bd
echo chor159-sop; grouper -p parameters.txt chor159-sop.nb > ../../boundaries/chor/chor159-sop.bd
echo chor160-sop; grouper -p parameters.txt chor160-sop.nb > ../../boundaries/chor/chor160-sop.bd
echo chor161-sop; grouper -p parameters.txt chor161-sop.nb > ../../boundaries/chor/chor161-sop.bd
echo chor162-sop; grouper -p parameters.txt chor162-sop.nb > ../../boundaries/chor/chor162-sop.bd
echo chor163-sop; grouper -p parameters.txt chor163-sop.nb > ../../boundaries/chor/chor163-sop.bd
echo chor164-sop; grouper -p parameters.txt chor164-sop.nb > ../../boundaries/chor/chor164-sop.bd
echo chor165-sop; grouper -p parameters.txt chor165-sop.nb > ../../boundaries/chor/chor165-sop.bd
echo chor166-sop; grouper -p parameters.txt chor166-sop.nb > ../../boundaries/chor/chor166-sop.bd
echo chor167-sop; grouper -p parameters.txt chor167-sop.nb > ../../boundaries/chor/chor167-sop.bd
echo chor168-sop; grouper -p parameters.txt chor168-sop.nb > ../../boundaries/chor/chor168-sop.bd
echo chor169-sop; grouper -p parameters.txt chor169-sop.nb > ../../boundaries/chor/chor169-sop.bd
echo chor170-sop; grouper -p parameters.txt chor170-sop.nb > ../../boundaries/chor/chor170-sop.bd
echo chor171-sop; grouper -p parameters.txt chor171-sop.nb > ../../boundaries/chor/chor171-sop.bd
echo chor172-sop; grouper -p parameters.txt chor172-sop.nb > ../../boundaries/chor/chor172-sop.bd
echo chor173-sop; grouper -p parameters.txt chor173-sop.nb > ../../boundaries/chor/chor173-sop.bd
echo chor174-sop; grouper -p parameters.txt chor174-sop.nb > ../../boundaries/chor/chor174-sop.bd
echo chor175-sop; grouper -p parameters.txt chor175-sop.nb > ../../boundaries/chor/chor175-sop.bd
echo chor176-sop; grouper -p parameters.txt chor176-sop.nb > ../../boundaries/chor/chor176-sop.bd
echo chor177-sop; grouper -p parameters.txt chor177-sop.nb > ../../boundaries/chor/chor177-sop.bd
echo chor178-sop; grouper -p parameters.txt chor178-sop.nb > ../../boundaries/chor/chor178-sop.bd
echo chor179-sop; grouper -p parameters.txt chor179-sop.nb > ../../boundaries/chor/chor179-sop.bd
echo chor180-sop; grouper -p parameters.txt chor180-sop.nb > ../../boundaries/chor/chor180-sop.bd
echo chor181-sop; grouper -p parameters.txt chor181-sop.nb > ../../boundaries/chor/chor181-sop.bd
echo chor182-sop; grouper -p parameters.txt chor182-sop.nb > ../../boundaries/chor/chor182-sop.bd
echo chor183-sop; grouper -p parameters.txt chor183-sop.nb > ../../boundaries/chor/chor183-sop.bd
echo chor184-sop; grouper -p parameters.txt chor184-sop.nb > ../../boundaries/chor/chor184-sop.bd
echo chor185-sop; grouper -p parameters.txt chor185-sop.nb > ../../boundaries/chor/chor185-sop.bd
echo chor186-sop; grouper -p parameters.txt chor186-sop.nb > ../../boundaries/chor/chor186-sop.bd
echo chor187-sop; grouper -p parameters.txt chor187-sop.nb > ../../boundaries/chor/chor187-sop.bd
echo chor188-sop; grouper -p parameters.txt chor188-sop.nb > ../../boundaries/chor/chor188-sop.bd
echo chor189-sop; grouper -p parameters.txt chor189-sop.nb > ../../boundaries/chor/chor189-sop.bd
echo chor190-sop; grouper -p parameters.txt chor190-sop.nb > ../../boundaries/chor/chor190-sop.bd
echo chor191-sop; grouper -p parameters.txt chor191-sop.nb > ../../boundaries/chor/chor191-sop.bd
echo chor192-sop; grouper -p parameters.txt chor192-sop.nb > ../../boundaries/chor/chor192-sop.bd
echo chor193-sop; grouper -p parameters.txt chor193-sop.nb > ../../boundaries/chor/chor193-sop.bd
echo chor194-sop; grouper -p parameters.txt chor194-sop.nb > ../../boundaries/chor/chor194-sop.bd
echo chor195-sop; grouper -p parameters.txt chor195-sop.nb > ../../boundaries/chor/chor195-sop.bd
echo chor196-sop; grouper -p parameters.txt chor196-sop.nb > ../../boundaries/chor/chor196-sop.bd
echo chor197-sop; grouper -p parameters.txt chor197-sop.nb > ../../boundaries/chor/chor197-sop.bd
echo chor198-sop; grouper -p parameters.txt chor198-sop.nb > ../../boundaries/chor/chor198-sop.bd
echo chor199-sop; grouper -p parameters.txt chor199-sop.nb > ../../boundaries/chor/chor199-sop.bd
echo chor200-sop; grouper -p parameters.txt chor200-sop.nb > ../../boundaries/chor/chor200-sop.bd
echo chor201-sop; grouper -p parameters.txt chor201-sop.nb > ../../boundaries/chor/chor201-sop.bd
echo chor202-sop; grouper -p parameters.txt chor202-sop.nb > ../../boundaries/chor/chor202-sop.bd
echo chor203-sop; grouper -p parameters.txt chor203-sop.nb > ../../boundaries/chor/chor203-sop.bd
echo chor204-sop; grouper -p parameters.txt chor204-sop.nb > ../../boundaries/chor/chor204-sop.bd
echo chor205-sop; grouper -p parameters.txt chor205-sop.nb > ../../boundaries/chor/chor205-sop.bd
echo chor206-sop; grouper -p parameters.txt chor206-sop.nb > ../../boundaries/chor/chor206-sop.bd
echo chor207-sop; grouper -p parameters.txt chor207-sop.nb > ../../boundaries/chor/chor207-sop.bd
echo chor208-sop; grouper -p parameters.txt chor208-sop.nb > ../../boundaries/chor/chor208-sop.bd
echo chor209-sop; grouper -p parameters.txt chor209-sop.nb > ../../boundaries/chor/chor209-sop.bd
echo chor210-sop; grouper -p parameters.txt chor210-sop.nb > ../../boundaries/chor/chor210-sop.bd
echo chor211-sop; grouper -p parameters.txt chor211-sop.nb > ../../boundaries/chor/chor211-sop.bd
echo chor212-sop; grouper -p parameters.txt chor212-sop.nb > ../../boundaries/chor/chor212-sop.bd
echo chor213-sop; grouper -p parameters.txt chor213-sop.nb > ../../boundaries/chor/chor213-sop.bd
echo chor214-sop; grouper -p parameters.txt chor214-sop.nb > ../../boundaries/chor/chor214-sop.bd
echo chor215-sop; grouper -p parameters.txt chor215-sop.nb > ../../boundaries/chor/chor215-sop.bd
echo chor216-sop; grouper -p parameters.txt chor216-sop.nb > ../../boundaries/chor/chor216-sop.bd
echo chor217-sop; grouper -p parameters.txt chor217-sop.nb > ../../boundaries/chor/chor217-sop.bd
echo chor218-sop; grouper -p parameters.txt chor218-sop.nb > ../../boundaries/chor/chor218-sop.bd
echo chor219-sop; grouper -p parameters.txt chor219-sop.nb > ../../boundaries/chor/chor219-sop.bd
echo chor220-sop; grouper -p parameters.txt chor220-sop.nb > ../../boundaries/chor/chor220-sop.bd
echo chor221-sop; grouper -p parameters.txt chor221-sop.nb > ../../boundaries/chor/chor221-sop.bd
echo chor222-sop; grouper -p parameters.txt chor222-sop.nb > ../../boundaries/chor/chor222-sop.bd
echo chor223-sop; grouper -p parameters.txt chor223-sop.nb > ../../boundaries/chor/chor223-sop.bd
echo chor224-sop; grouper -p parameters.txt chor224-sop.nb > ../../boundaries/chor/chor224-sop.bd
echo chor225-sop; grouper -p parameters.txt chor225-sop.nb > ../../boundaries/chor/chor225-sop.bd
echo chor226-sop; grouper -p parameters.txt chor226-sop.nb > ../../boundaries/chor/chor226-sop.bd
echo chor227-sop; grouper -p parameters.txt chor227-sop.nb > ../../boundaries/chor/chor227-sop.bd
echo chor228-sop; grouper -p parameters.txt chor228-sop.nb > ../../boundaries/chor/chor228-sop.bd
echo chor229-sop; grouper -p parameters.txt chor229-sop.nb > ../../boundaries/chor/chor229-sop.bd
echo chor230-sop; grouper -p parameters.txt chor230-sop.nb > ../../boundaries/chor/chor230-sop.bd
echo chor231-sop; grouper -p parameters.txt chor231-sop.nb > ../../boundaries/chor/chor231-sop.bd
echo chor232-sop; grouper -p parameters.txt chor232-sop.nb > ../../boundaries/chor/chor232-sop.bd
echo chor233-sop; grouper -p parameters.txt chor233-sop.nb > ../../boundaries/chor/chor233-sop.bd
echo chor234-sop; grouper -p parameters.txt chor234-sop.nb > ../../boundaries/chor/chor234-sop.bd
echo chor235-sop; grouper -p parameters.txt chor235-sop.nb > ../../boundaries/chor/chor235-sop.bd
echo chor236-sop; grouper -p parameters.txt chor236-sop.nb > ../../boundaries/chor/chor236-sop.bd
echo chor237-sop; grouper -p parameters.txt chor237-sop.nb > ../../boundaries/chor/chor237-sop.bd
echo chor238-sop; grouper -p parameters.txt chor238-sop.nb > ../../boundaries/chor/chor238-sop.bd
echo chor239-sop; grouper -p parameters.txt chor239-sop.nb > ../../boundaries/chor/chor239-sop.bd
echo chor240-sop; grouper -p parameters.txt chor240-sop.nb > ../../boundaries/chor/chor240-sop.bd
echo chor241-sop; grouper -p parameters.txt chor241-sop.nb > ../../boundaries/chor/chor241-sop.bd
echo chor242-sop; grouper -p parameters.txt chor242-sop.nb > ../../boundaries/chor/chor242-sop.bd
echo chor243-sop; grouper -p parameters.txt chor243-sop.nb > ../../boundaries/chor/chor243-sop.bd
echo chor244-sop; grouper -p parameters.txt chor244-sop.nb > ../../boundaries/chor/chor244-sop.bd
echo chor245-sop; grouper -p parameters.txt chor245-sop.nb > ../../boundaries/chor/chor245-sop.bd
echo chor246-sop; grouper -p parameters.txt chor246-sop.nb > ../../boundaries/chor/chor246-sop.bd
echo chor247-sop; grouper -p parameters.txt chor247-sop.nb > ../../boundaries/chor/chor247-sop.bd
echo chor248-sop; grouper -p parameters.txt chor248-sop.nb > ../../boundaries/chor/chor248-sop.bd
echo chor249-sop; grouper -p parameters.txt chor249-sop.nb > ../../boundaries/chor/chor249-sop.bd
echo chor250-sop; grouper -p parameters.txt chor250-sop.nb > ../../boundaries/chor/chor250-sop.bd
echo chor251-sop; grouper -p parameters.txt chor251-sop.nb > ../../boundaries/chor/chor251-sop.bd
echo chor252-sop; grouper -p parameters.txt chor252-sop.nb > ../../boundaries/chor/chor252-sop.bd
echo chor253-sop; grouper -p parameters.txt chor253-sop.nb > ../../boundaries/chor/chor253-sop.bd
echo chor254-sop; grouper -p parameters.txt chor254-sop.nb > ../../boundaries/chor/chor254-sop.bd
echo chor255-sop; grouper -p parameters.txt chor255-sop.nb > ../../boundaries/chor/chor255-sop.bd
echo chor256-sop; grouper -p parameters.txt chor256-sop.nb > ../../boundaries/chor/chor256-sop.bd
echo chor257-sop; grouper -p parameters.txt chor257-sop.nb > ../../boundaries/chor/chor257-sop.bd
echo chor258-sop; grouper -p parameters.txt chor258-sop.nb > ../../boundaries/chor/chor258-sop.bd
echo chor259-sop; grouper -p parameters.txt chor259-sop.nb > ../../boundaries/chor/chor259-sop.bd
echo chor260-sop; grouper -p parameters.txt chor260-sop.nb > ../../boundaries/chor/chor260-sop.bd
echo chor261-sop; grouper -p parameters.txt chor261-sop.nb > ../../boundaries/chor/chor261-sop.bd
echo chor262-sop; grouper -p parameters.txt chor262-sop.nb > ../../boundaries/chor/chor262-sop.bd
echo chor263-sop; grouper -p parameters.txt chor263-sop.nb > ../../boundaries/chor/chor263-sop.bd
echo chor264-sop; grouper -p parameters.txt chor264-sop.nb > ../../boundaries/chor/chor264-sop.bd
echo chor265-sop; grouper -p parameters.txt chor265-sop.nb > ../../boundaries/chor/chor265-sop.bd
echo chor266-sop; grouper -p parameters.txt chor266-sop.nb > ../../boundaries/chor/chor266-sop.bd
echo chor267-sop; grouper -p parameters.txt chor267-sop.nb > ../../boundaries/chor/chor267-sop.bd
echo chor268-sop; grouper -p parameters.txt chor268-sop.nb > ../../boundaries/chor/chor268-sop.bd
echo chor269-sop; grouper -p parameters.txt chor269-sop.nb > ../../boundaries/chor/chor269-sop.bd
echo chor270-sop; grouper -p parameters.txt chor270-sop.nb > ../../boundaries/chor/chor270-sop.bd
echo chor271-sop; grouper -p parameters.txt chor271-sop.nb > ../../boundaries/chor/chor271-sop.bd
echo chor272-sop; grouper -p parameters.txt chor272-sop.nb > ../../boundaries/chor/chor272-sop.bd
echo chor273-sop; grouper -p parameters.txt chor273-sop.nb > ../../boundaries/chor/chor273-sop.bd
echo chor274-sop; grouper -p parameters.txt chor274-sop.nb > ../../boundaries/chor/chor274-sop.bd
echo chor275-sop; grouper -p parameters.txt chor275-sop.nb > ../../boundaries/chor/chor275-sop.bd
echo chor276-sop; grouper -p parameters.txt chor276-sop.nb > ../../boundaries/chor/chor276-sop.bd
echo chor277-sop; grouper -p parameters.txt chor277-sop.nb > ../../boundaries/chor/chor277-sop.bd
echo chor278-sop; grouper -p parameters.txt chor278-sop.nb > ../../boundaries/chor/chor278-sop.bd
echo chor279-sop; grouper -p parameters.txt chor279-sop.nb > ../../boundaries/chor/chor279-sop.bd
echo chor280-sop; grouper -p parameters.txt chor280-sop.nb > ../../boundaries/chor/chor280-sop.bd
echo chor281-sop; grouper -p parameters.txt chor281-sop.nb > ../../boundaries/chor/chor281-sop.bd
echo chor282-sop; grouper -p parameters.txt chor282-sop.nb > ../../boundaries/chor/chor282-sop.bd
echo chor283-sop; grouper -p parameters.txt chor283-sop.nb > ../../boundaries/chor/chor283-sop.bd
echo chor284-sop; grouper -p parameters.txt chor284-sop.nb > ../../boundaries/chor/chor284-sop.bd
echo chor285-sop; grouper -p parameters.txt chor285-sop.nb > ../../boundaries/chor/chor285-sop.bd
echo chor286-sop; grouper -p parameters.txt chor286-sop.nb > ../../boundaries/chor/chor286-sop.bd
echo chor287-sop; grouper -p parameters.txt chor287-sop.nb > ../../boundaries/chor/chor287-sop.bd
echo chor288-sop; grouper -p parameters.txt chor288-sop.nb > ../../boundaries/chor/chor288-sop.bd
echo chor289-sop; grouper -p parameters.txt chor289-sop.nb > ../../boundaries/chor/chor289-sop.bd
echo chor290-sop; grouper -p parameters.txt chor290-sop.nb > ../../boundaries/chor/chor290-sop.bd
echo chor291-sop; grouper -p parameters.txt chor291-sop.nb > ../../boundaries/chor/chor291-sop.bd
echo chor292-sop; grouper -p parameters.txt chor292-sop.nb > ../../boundaries/chor/chor292-sop.bd
echo chor293-sop; grouper -p parameters.txt chor293-sop.nb > ../../boundaries/chor/chor293-sop.bd
echo chor294-sop; grouper -p parameters.txt chor294-sop.nb > ../../boundaries/chor/chor294-sop.bd
echo chor295-sop; grouper -p parameters.txt chor295-sop.nb > ../../boundaries/chor/chor295-sop.bd
echo chor296-sop; grouper -p parameters.txt chor296-sop.nb > ../../boundaries/chor/chor296-sop.bd
echo chor297-sop; grouper -p parameters.txt chor297-sop.nb > ../../boundaries/chor/chor297-sop.bd
echo chor298-sop; grouper -p parameters.txt chor298-sop.nb > ../../boundaries/chor/chor298-sop.bd
echo chor299-sop; grouper -p parameters.txt chor299-sop.nb > ../../boundaries/chor/chor299-sop.bd
echo chor300-sop; grouper -p parameters.txt chor300-sop.nb > ../../boundaries/chor/chor300-sop.bd
echo chor301-sop; grouper -p parameters.txt chor301-sop.nb > ../../boundaries/chor/chor301-sop.bd
echo chor302-sop; grouper -p parameters.txt chor302-sop.nb > ../../boundaries/chor/chor302-sop.bd
echo chor303-sop; grouper -p parameters.txt chor303-sop.nb > ../../boundaries/chor/chor303-sop.bd
echo chor304-sop; grouper -p parameters.txt chor304-sop.nb > ../../boundaries/chor/chor304-sop.bd
echo chor305-sop; grouper -p parameters.txt chor305-sop.nb > ../../boundaries/chor/chor305-sop.bd
echo chor306-sop; grouper -p parameters.txt chor306-sop.nb > ../../boundaries/chor/chor306-sop.bd
echo chor307-sop; grouper -p parameters.txt chor307-sop.nb > ../../boundaries/chor/chor307-sop.bd
echo chor308-sop; grouper -p parameters.txt chor308-sop.nb > ../../boundaries/chor/chor308-sop.bd
echo chor309-sop; grouper -p parameters.txt chor309-sop.nb > ../../boundaries/chor/chor309-sop.bd
echo chor310-sop; grouper -p parameters.txt chor310-sop.nb > ../../boundaries/chor/chor310-sop.bd
echo chor311-sop; grouper -p parameters.txt chor311-sop.nb > ../../boundaries/chor/chor311-sop.bd
echo chor312-sop; grouper -p parameters.txt chor312-sop.nb > ../../boundaries/chor/chor312-sop.bd
echo chor313-sop; grouper -p parameters.txt chor313-sop.nb > ../../boundaries/chor/chor313-sop.bd
echo chor314-sop; grouper -p parameters.txt chor314-sop.nb > ../../boundaries/chor/chor314-sop.bd
echo chor315-sop; grouper -p parameters.txt chor315-sop.nb > ../../boundaries/chor/chor315-sop.bd
echo chor316-sop; grouper -p parameters.txt chor316-sop.nb > ../../boundaries/chor/chor316-sop.bd
echo chor317-sop; grouper -p parameters.txt chor317-sop.nb > ../../boundaries/chor/chor317-sop.bd
echo chor318-sop; grouper -p parameters.txt chor318-sop.nb > ../../boundaries/chor/chor318-sop.bd
echo chor319-sop; grouper -p parameters.txt chor319-sop.nb > ../../boundaries/chor/chor319-sop.bd
echo chor320-sop; grouper -p parameters.txt chor320-sop.nb > ../../boundaries/chor/chor320-sop.bd
echo chor321-sop; grouper -p parameters.txt chor321-sop.nb > ../../boundaries/chor/chor321-sop.bd
echo chor322-sop; grouper -p parameters.txt chor322-sop.nb > ../../boundaries/chor/chor322-sop.bd
echo chor323-sop; grouper -p parameters.txt chor323-sop.nb > ../../boundaries/chor/chor323-sop.bd
echo chor324-sop; grouper -p parameters.txt chor324-sop.nb > ../../boundaries/chor/chor324-sop.bd
echo chor325-sop; grouper -p parameters.txt chor325-sop.nb > ../../boundaries/chor/chor325-sop.bd
echo chor326-sop; grouper -p parameters.txt chor326-sop.nb > ../../boundaries/chor/chor326-sop.bd
echo chor327-sop; grouper -p parameters.txt chor327-sop.nb > ../../boundaries/chor/chor327-sop.bd
echo chor328-sop; grouper -p parameters.txt chor328-sop.nb > ../../boundaries/chor/chor328-sop.bd
echo chor329-sop; grouper -p parameters.txt chor329-sop.nb > ../../boundaries/chor/chor329-sop.bd
echo chor330-sop; grouper -p parameters.txt chor330-sop.nb > ../../boundaries/chor/chor330-sop.bd
echo chor331-sop; grouper -p parameters.txt chor331-sop.nb > ../../boundaries/chor/chor331-sop.bd
echo chor332-sop; grouper -p parameters.txt chor332-sop.nb > ../../boundaries/chor/chor332-sop.bd
echo chor333-sop; grouper -p parameters.txt chor333-sop.nb > ../../boundaries/chor/chor333-sop.bd
echo chor334-sop; grouper -p parameters.txt chor334-sop.nb > ../../boundaries/chor/chor334-sop.bd
echo chor335-sop; grouper -p parameters.txt chor335-sop.nb > ../../boundaries/chor/chor335-sop.bd
echo chor336-sop; grouper -p parameters.txt chor336-sop.nb > ../../boundaries/chor/chor336-sop.bd
echo chor337-sop; grouper -p parameters.txt chor337-sop.nb > ../../boundaries/chor/chor337-sop.bd
echo chor338-sop; grouper -p parameters.txt chor338-sop.nb > ../../boundaries/chor/chor338-sop.bd
echo chor339-sop; grouper -p parameters.txt chor339-sop.nb > ../../boundaries/chor/chor339-sop.bd
echo chor340-sop; grouper -p parameters.txt chor340-sop.nb > ../../boundaries/chor/chor340-sop.bd
echo chor341-sop; grouper -p parameters.txt chor341-sop.nb > ../../boundaries/chor/chor341-sop.bd
echo chor342-sop; grouper -p parameters.txt chor342-sop.nb > ../../boundaries/chor/chor342-sop.bd
echo chor343-sop; grouper -p parameters.txt chor343-sop.nb > ../../boundaries/chor/chor343-sop.bd
echo chor344-sop; grouper -p parameters.txt chor344-sop.nb > ../../boundaries/chor/chor344-sop.bd
echo chor345-sop; grouper -p parameters.txt chor345-sop.nb > ../../boundaries/chor/chor345-sop.bd
echo chor346-sop; grouper -p parameters.txt chor346-sop.nb > ../../boundaries/chor/chor346-sop.bd
echo chor347-sop; grouper -p parameters.txt chor347-sop.nb > ../../boundaries/chor/chor347-sop.bd
echo chor348-sop; grouper -p parameters.txt chor348-sop.nb > ../../boundaries/chor/chor348-sop.bd
echo chor349-sop; grouper -p parameters.txt chor349-sop.nb > ../../boundaries/chor/chor349-sop.bd
echo chor350-sop; grouper -p parameters.txt chor350-sop.nb > ../../boundaries/chor/chor350-sop.bd
echo chor351-sop; grouper -p parameters.txt chor351-sop.nb > ../../boundaries/chor/chor351-sop.bd
echo chor352-sop; grouper -p parameters.txt chor352-sop.nb > ../../boundaries/chor/chor352-sop.bd
echo chor353-sop; grouper -p parameters.txt chor353-sop.nb > ../../boundaries/chor/chor353-sop.bd
echo chor354-sop; grouper -p parameters.txt chor354-sop.nb > ../../boundaries/chor/chor354-sop.bd
echo chor355-sop; grouper -p parameters.txt chor355-sop.nb > ../../boundaries/chor/chor355-sop.bd
echo chor356-sop; grouper -p parameters.txt chor356-sop.nb > ../../boundaries/chor/chor356-sop.bd
echo chor357-sop; grouper -p parameters.txt chor357-sop.nb > ../../boundaries/chor/chor357-sop.bd
echo chor358-sop; grouper -p parameters.txt chor358-sop.nb > ../../boundaries/chor/chor358-sop.bd
echo chor359-sop; grouper -p parameters.txt chor359-sop.nb > ../../boundaries/chor/chor359-sop.bd
echo chor360-sop; grouper -p parameters.txt chor360-sop.nb > ../../boundaries/chor/chor360-sop.bd
echo chor361-sop; grouper -p parameters.txt chor361-sop.nb > ../../boundaries/chor/chor361-sop.bd
echo chor362-sop; grouper -p parameters.txt chor362-sop.nb > ../../boundaries/chor/chor362-sop.bd
echo chor363-sop; grouper -p parameters.txt chor363-sop.nb > ../../boundaries/chor/chor363-sop.bd
echo chor364-sop; grouper -p parameters.txt chor364-sop.nb > ../../boundaries/chor/chor364-sop.bd
echo chor365-sop; grouper -p parameters.txt chor365-sop.nb > ../../boundaries/chor/chor365-sop.bd
echo chor366-sop; grouper -p parameters.txt chor366-sop.nb > ../../boundaries/chor/chor366-sop.bd
echo chor367-sop; grouper -p parameters.txt chor367-sop.nb > ../../boundaries/chor/chor367-sop.bd
echo chor368-sop; grouper -p parameters.txt chor368-sop.nb > ../../boundaries/chor/chor368-sop.bd
echo chor369-sop; grouper -p parameters.txt chor369-sop.nb > ../../boundaries/chor/chor369-sop.bd
echo chor370-sop; grouper -p parameters.txt chor370-sop.nb > ../../boundaries/chor/chor370-sop.bd
echo chor371-sop; grouper -p parameters.txt chor371-sop.nb > ../../boundaries/chor/chor371-sop.bd
